changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: 🐛 Bug Fixes
      labels:
        - bug
    - title: ⬆️ Dependencies
      labels:
        - dependencies
    - title: 📝 Documentation
      labels:
        - documentation
    - title: 🎉 Exciting New Features
      labels:
        - enhancement
    - title: ⚙️ GitHub Actions
      labels:
        - github_actions
    - title: 🧩 Other Changes
      labels:
        - "*"
