name: Setup SSH

description: Sets up SSH keys and known_hosts

inputs:
  ssh_key:
    required: true
    description: SSH private key
  ssh_host:
    required: true
    description: SSH host

runs:
  using: "composite"
  steps:
    - run: |
        mkdir -p ~/.ssh
        echo "${{ inputs.ssh_key }}" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan -H ${{ inputs.ssh_host }} >> ~/.ssh/known_hosts
      shell: bash