name: Setup Gradle

description: Sets up Java and Gradle for building projects.

runs:
  using: "composite"
  steps:
    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Make Gradle Wrapper Executable
      run: chmod +x ./gradlew
      shell: bash
