name: Start Remote Service

on:
  workflow_dispatch:
  workflow_call:

jobs:
  stop-service:
    runs-on: ubuntu-latest
    steps:
      - name: Start service on remote server
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "sudo systemctl start ${{ secrets.SERVICE_NAME }}"